export interface Label {
  id: string;
  name: string;
}

export const LABELS: Label[] = [
  { id: "abigender",              name: "Abigender" },
  { id: "abroflux",               name: "Abroflux" },
  { id: "achillean",              name: "Achillean" },
  { id: "aceflux",                name: "Aceflux" },
  { id: "aegosexual",             name: "Aegosexual" },
  { id: "afamilial",              name: "Afamilial" },
  { id: "agender",                name: "Agender" },
  { id: "alloace",                name: "Alloace" },
  { id: "androgynous",            name: "Androgynous" },
  { id: "apagender",              name: "Apagender" },
  { id: "apothiromantic",         name: "Apothiromantic" },
  { id: "apothisexual",           name: "Apothisexual" },
  { id: "aroaceflux",             name: "Aroaceflux" },
  { id: "aroallo",                name: "Aroallo" },
  { id: "aroflux",                name: "Aroflux" },
  { id: "aromantic",              name: "Aromantic" },
  { id: "aromantic-asexual",      name: "Aromantic-Asexual" },
  { id: "arospike",               name: "Arospike" },
  { id: "asexual",                name: "Asexual" },
  { id: "autiboy",                name: "Autiboy" },
  { id: "autigender",             name: "Autigender" },
  { id: "autigirl",               name: "Autigirl" },
  { id: "bigender",               name: "Bigender" },
  { id: "biromantic",             name: "Biromantic" },
  { id: "bisexual",               name: "Bisexual" },
  { id: "boyflux",                name: "Boyflux" },
  { id: "catgender",              name: "Catgender" },
  { id: "check-bio",              name: "Check Bio" },
  { id: "cupiosexual",            name: "Cupiosexual" },
  { id: "cupioromantic",          name: "Cupioromantic" },
  { id: "demiboy",                name: "Demiboy" },
  { id: "demifluid",              name: "Demifluid" },
  { id: "demifluix",              name: "Demifluix" },
  { id: "demiflux",               name: "Demiflux" },
  { id: "demigender",             name: "Demigender" },
  { id: "demigirl",               name: "Demigirl" },
  { id: "demiromantic",           name: "Demiromantic" },
  { id: "demirose",               name: "Demirose" },
  { id: "demisexual",             name: "Demisexual" },
  { id: "fluidflux",              name: "Fluidflux" },
  { id: "gay",                    name: "Gay" },
  { id: "gender-non-conforming",  name: "Gender Non-Conforming" },
  { id: "genderfae",              name: "Genderfae" },
  { id: "genderfaun",             name: "Genderfaun" },
  { id: "genderfluid",            name: "Genderfluid" },
  { id: "genderflux",             name: "Genderflux" },
  { id: "genderless",             name: "Genderless" },
  { id: "genderqueer",            name: "Genderqueer" },
  { id: "girlflux",               name: "Girlflux" },
  { id: "grayromantic",           name: "Grayromantic" },
  { id: "graysexual",             name: "Graysexual" },
  { id: "idemromantic",           name: "Idemromantic" },
  { id: "intersex",               name: "Intersex" },
  { id: "juxera",                 name: "Juxera" },
  { id: "lesbian",                name: "Lesbian" },
  { id: "lgbtqia-safe-space",     name: "LGBTQIA+ Safe Space" },
  { id: "mothogender",            name: "Mothogender" },
  { id: "multigender",            name: "Multigender" },
  { id: "neptunic",               name: "Neptunic" },
  { id: "non-binary",             name: "Non-Binary" },
  { id: "omnisexual",             name: "Omnisexual" },
  { id: "oriented-aroace",        name: "Oriented Aroace" },
  { id: "pangender",              name: "Pangender" },
  { id: "panromantic",            name: "Panromantic" },
  { id: "pansexual",              name: "Pansexual" },
  { id: "polyamorous",            name: "Polyamorous" },
  { id: "polygender",             name: "Polygender" },
  { id: "proxvir",                name: "Proxvir" },
  { id: "queer",                  name: "Queer" },
  { id: "queerplatonic",          name: "Queerplatonic" },
  { id: "questioning",            name: "Questioning" },
  { id: "quoiflux",               name: "Quoiflux" },
  { id: "quoigender",             name: "Quoigender" },
  { id: "quoiroflux",             name: "Quoiroflux" },
  { id: "quoiromantic",           name: "Quoiromantic" },
  { id: "quoisexual",             name: "Quoisexual" },
  { id: "sapphic",                name: "Sapphic" },
  { id: "trans-loving-trans",     name: "Trans Loving Trans" },
  { id: "transfeminine",          name: "Transfeminine" },
  { id: "transmasculine",         name: "Transmasculine" },
  { id: "transneutral",           name: "Transneutral" },
  { id: "transgender",            name: "Transgender" },
  { id: "unlabeled",              name: "Unlabeled" },
  { id: "xenogender",             name: "Xenogender" },
];

// Derived set used for validation in Pages Functions
export const LABEL_IDS: Set<string> = new Set(LABELS.map(l => l.id));